
FROM debian:stable-slim
RUN useradd -m app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /home/app
USER app
COPY --chown=app:app ./bin/cosmoverse /home/app/cosmoverse
ENTRYPOINT ["./cosmoverse"]
