
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cosmoverse.fullname" . }}-deny-all
spec:
  podSelector:
    matchLabels: {{- include "cosmoverse.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress","Egress"]
{{- end }}
