
blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/your-org/cosmoverse-engine/security/policy
    about: Please report vulnerabilities via our SECURITY policy.
