
image:
  repository: ghcr.io/your-org/cosmoverse-engine
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
podSecurityContext:
  runAsNonRoot: true
  seccompProfile: { type: RuntimeDefault }
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities: { drop: [ "ALL" ] }
resources:
  requests: { cpu: 100m, memory: 64Mi }
  limits: { cpu: 500m, memory: 256Mi }
service:
  type: ClusterIP
  port: 8080
networkPolicy:
  enabled: true
