
name: ABI Compliance (best-effort)
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y abi-dumper abi-compliance-checker libbfd-dev binutils
      - name: Build shared lib
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          cmake --build build -j
      - name: Dump ABI
        run: |
          libfile=$(find build -name "lib*.so" | head -n1 || true)
          if [ -z "$libfile" ]; then echo "No shared lib found; skipping"; exit 0; fi
          abi-dumper "$libfile" -o ABI-NEW.dump -lver NEW || true
      - name: Compare (if baseline present)
        run: |
          if [ -f ABI-BASE.dump ]; then
            abi-compliance-checker -l cosmoverse -old ABI-BASE.dump -new ABI-NEW.dump || true
          else
            echo "No ABI baseline; upload NEW as artifact"
          fi
