
name: actionlint
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v1
