
name: Config Lint
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: python3 scripts/config_lint.py || true
