
name: Container Build & Sign (keyless)
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  packages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sign:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3.6.0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.title=COSMOVERSE
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=Apache-2.0
      - name: Sign
        env: { COSIGN_EXPERIMENTAL: "true" }
        run: cosign sign --yes ghcr.io/${{ github.repository }}:latest
      - name: Attest (provenance)
        env: { COSIGN_EXPERIMENTAL: "true" }
        run: cosign attest --predicate sbom.cdx.json --type cyclonedx --yes ghcr.io/${{ github.repository }}:latest || true
