
name: Coverage Gate
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y lcov
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCOSMO_COVERAGE=ON
      - run: cmake --build build -j
      - run: ctest --test-dir build --output-on-failure || true
      - run: lcov --capture --directory build --output-file coverage.info || true
      - run: lcov --remove coverage.info '/usr/*' --output-file coverage.info || true
      - run: python3 scripts/coverage_gate.py 50
