
name: Docs Quality
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pip install codespell yamllint markdownlint-cli2
      - run: codespell -S .git,build,dist,site --quiet-level=2 || true
      - run: yamllint . || true
      - run: npx markdownlint-cli2 "**/*.md" "#node_modules" || true
