
name: Docs Language Hint
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: python3 scripts/docs_language_check.py || true
