
name: Release
on:
  workflow_dispatch:
  push:
    tags: ['v*']
permissions:
  contents: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Package
        run: cmake -S . -B build -DCPACK_GENERATOR=ZIP && cmake --build build --target package
      - name: Checksums
        run: bash scripts/checksums.sh
      - name: SBOM
        run: bash scripts/generate_sbom.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cosmoverse-${{ matrix.os }}
          path: build/*.zip
      - uses: sigstore/cosign-installer@v3.5.0
      - name: Cosign sign artifacts (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          for f in build/*.zip; do cosign sign-blob --yes "$f" --output-signature "$f.sig"; done
  ghcr-image:
    \1    continue-on-error: true
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/cosmoverse:{{ github.ref_name }}
  provenance:
    needs: build-release
    \1    continue-on-error: true
    permissions: { actions: read, id-token: write, contents: write }
    steps:
      - uses: slsa-framework/slsa-github-generator/.github/actions/generator@v2.0.0
        with:
          attestation-name: "slsa-provenance.intoto.jsonl"


trivy-image:
  needs: ghcr-image
  \1    continue-on-error: true
  steps:
    - uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: ghcr.io/${{ github.repository }}/cosmoverse:${{ github.ref_name }}
        format: 'table'
        exit-code: '0'

sign-image:
  needs: ghcr-image
  permissions:
    id-token: write
    packages: write
    contents: read
  \1    continue-on-error: true
  steps:
    - uses: sigstore/cosign-installer@v3.5.0
    - name: Cosign sign (keyless)
      env:
        COSIGN_EXPERIMENTAL: "1"
      run: cosign sign --yes ghcr.io/${{ github.repository }}/cosmoverse:${{ github.ref_name }}
