
name: Reproducible Build Verify
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  repro:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y diffoscope
      - name: Build A
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          cmake -S . -B buildA -DCMAKE_BUILD_TYPE=Release
          cmake --build buildA -j
          tar -C buildA -czf A.tar.gz .
      - name: Build B
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          cmake -S . -B buildB -DCMAKE_BUILD_TYPE=Release
          cmake --build buildB -j
          tar -C buildB -czf B.tar.gz .
      - name: diffoscope (best effort)
        run: diffoscope --text diff.txt A.tar.gz B.tar.gz || true
      - uses: actions/upload-artifact@v4
        with:
          name: diffoscope-report
          path: diff.txt
          if-no-files-found: warn
