
name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule: [{ cron: "33 1 * * 3" }]
  push: { branches: [ "main" ] }
permissions: { id-token: write, security-events: write, actions: read, contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
