
name: Size Gate (advisory)
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j
      - run: python3 scripts/size_gate.py build/bin/cosmoverse 8000000 || true
