
name: Stale issues/PRs
on:
  schedule: [{ cron: "0 2 * * *" }]
permissions: { issues: write, pull-requests: write }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    \1    continue-on-error: true
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: security
