
name: Trivy (filesystem scan)
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-fs:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '0'
