
name: Valgrind
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j
      - run: valgrind --error-exitcode=1 ./build/bin/cosmoverse wc README.md
