
name: WASI (advisory)
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasi:
    \1    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install wasi-sdk
        run: |
          sudo mkdir -p /opt/wasi-sdk && cd /opt/wasi-sdk
          curl -sL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-21/wasi-sdk-21.0-linux.tar.gz | sudo tar xz --strip-components=1
      - name: Build
        run: |
          export WASI_SDK_PATH=/opt/wasi-sdk
          cmake -S . -B build-wasi -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/wasi.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCOSMO_BUILD_SHARED=OFF
          cmake --build build-wasi -j || true
