
name: Windows MSI (WiX, advisory)
on: [workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j
      - name: Install WiX
        run: choco install wixtoolset -y
      - name: Heat and Candle
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe" dir build\bin -cg Binaries -dr INSTALLFOLDER -sfrag -srd -sreg -out packaging\windows\wix\Binaries.wxs
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" packaging\windows\wix\*.wxs -out wix\
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" wix\*.wixobj -o cosmoverse.msi
      - uses: actions/upload-artifact@v4
        with:
          name: cosmoverse-msi
          path: cosmoverse.msi
